"""add deck sharing fields

Revision ID: 1fdc68513499
Revises: 18d645d2d8b3
Create Date: 2025-12-06 05:12:47.448849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fdc68513499'
down_revision: Union[str, Sequence[str], None] = '18d645d2d8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcard_decks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('flashcard_decks', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('flashcard_decks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('flashcard_decks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_flashcard_decks_is_public'), 'flashcard_decks', ['is_public'], unique=False)
    op.alter_column('flashcards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('flashcards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('flashcards', 'last_review',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('flashcards', 'due',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"))
    op.drop_index(op.f('ix_gloss_text_trgm'), table_name='gloss', postgresql_ops={'lower(text::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gloss_text_trgm'), 'gloss', [sa.literal_column('lower(text::text)')], unique=False, postgresql_ops={'lower(text::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('flashcards', 'due',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text)"))
    op.alter_column('flashcards', 'last_review',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('flashcards', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('flashcards', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_flashcard_decks_is_public'), table_name='flashcard_decks')
    op.alter_column('flashcard_decks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('flashcard_decks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('flashcard_decks', 'is_public')
    op.drop_column('flashcard_decks', 'description')
    # ### end Alembic commands ###
