"""add indexes for search optimization

Revision ID: 212a837af98d
Revises: dbe8725dca05
Create Date: 2025-12-04 05:42:27.614335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212a837af98d'
down_revision: Union[str, Sequence[str], None] = 'dbe8725dca05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entry_is_common'), 'entry', ['is_common'], unique=False)
    op.create_index(op.f('ix_entry_jlpt_level'), 'entry', ['jlpt_level'], unique=False)
    op.create_index(op.f('ix_example_sense_id'), 'example', ['sense_id'], unique=False)
    op.create_index(op.f('ix_gloss_lang'), 'gloss', ['lang'], unique=False)
    op.create_index(op.f('ix_gloss_sense_id'), 'gloss', ['sense_id'], unique=False)
    op.create_index(op.f('ix_gloss_text'), 'gloss', ['text'], unique=False)
    op.create_index(op.f('ix_kanji_entry_id'), 'kanji', ['entry_id'], unique=False)
    op.create_index(op.f('ix_kanji_keb'), 'kanji', ['keb'], unique=False)
    op.create_index(op.f('ix_reading_entry_id'), 'reading', ['entry_id'], unique=False)
    op.create_index(op.f('ix_reading_reb'), 'reading', ['reb'], unique=False)
    op.create_index(op.f('ix_sense_entry_id'), 'sense', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sense_entry_id'), table_name='sense')
    op.drop_index(op.f('ix_reading_reb'), table_name='reading')
    op.drop_index(op.f('ix_reading_entry_id'), table_name='reading')
    op.drop_index(op.f('ix_kanji_keb'), table_name='kanji')
    op.drop_index(op.f('ix_kanji_entry_id'), table_name='kanji')
    op.drop_index(op.f('ix_gloss_text'), table_name='gloss')
    op.drop_index(op.f('ix_gloss_sense_id'), table_name='gloss')
    op.drop_index(op.f('ix_gloss_lang'), table_name='gloss')
    op.drop_index(op.f('ix_example_sense_id'), table_name='example')
    op.drop_index(op.f('ix_entry_jlpt_level'), table_name='entry')
    op.drop_index(op.f('ix_entry_is_common'), table_name='entry')
    # ### end Alembic commands ###
