"""Add flashcard tables

Revision ID: dbe8725dca05
Revises: 
Create Date: 2025-11-27 15:50:44.440298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbe8725dca05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('ent_seq', sa.Integer(), nullable=False),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.Column('jlpt_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('ent_seq')
    )
    op.create_table('flashcard_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_decks_user_id'), 'flashcard_decks', ['user_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('front', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('back', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_deck_id'), 'flashcards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_flashcards_user_id'), 'flashcards', ['user_id'], unique=False)
    op.create_table('kanji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keb', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ke_inf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ke_pri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.ent_seq'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reb', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('re_nokanji', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('re_pri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('re_inf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.ent_seq'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('pos', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('misc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.ent_seq'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['sense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gloss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sense_id', sa.Integer(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['sense_id'], ['sense.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gloss')
    op.drop_table('example')
    op.drop_table('sense')
    op.drop_table('reading')
    op.drop_table('kanji')
    op.drop_index(op.f('ix_flashcards_user_id'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_deck_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_flashcard_decks_user_id'), table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    op.drop_table('entry')
    # ### end Alembic commands ###
